public class FormUtils {
    public class FormData{
        @AuraEnabled
        public Contact primaryContact {get;set;}
        @AuraEnabled
        public Opportunity opp{get;set;}
       /*   @AuraEnabled   
       public Boolean SPPRemoved {get;set;}
        @AuraEnabled
        Public Contact spouseContact{get;set;}
        @AuraEnabled
        public PackageDetail selectedPackage{get;set;}
        @AuraEnabled
        public PackageDetail originalPackage{get;set;}

        @AuraEnabled
        Public String leadIdFromSpouseSearch{get;set;}
        @AuraEnabled
        Public String currentNextTransactionDate{get;set;}
        @AuraEnabled
        Public Date oneTimeFutureSubscriptionDate{get;set;}
        @AuraEnabled
        Public Date extendedDateofSubscription{get;set;}
        @AuraEnabled
        Public Integer numberOfMonthsSubscriptionExtended{get;set;}
        @AuraEnabled
        Public String finalActionType{get;set;}
        
        @AuraEnabled
        Public List<SelectOption> downShellPackages{get;set;}
        @AuraEnabled
        Public List<SelectOption> upgradedPackages{get;set;}
        @AuraEnabled
        Public CreditCardWrap creditCardInfo{get;set;}
        @AuraEnabled
        Public CreditCardWrap secondCreditCardInfo{get;set;}
        @AuraEnabled
        Public Turn_Off_Turn_On_API__c api{get;set;}
        @AuraEnabled
        Public Boolean isLeadConverted{get;set;}
        @AuraEnabled
        Public String spouseContactId{get;set;}
*/
        
        
        
        public FormData(){}
    }
    
}